### ISSUE TITLE
安装一切正常但是 F6 和 F5 没有反应

### ISSUE THREAD

**Issue by cc1477** [Guyutongxue/vscch4#46]
Ctrl + Shitf + B 可以编译但是无法正常运行

**Comment by guyutongxue** [comment]
你键盘上是否有 Fn 键？

**Comment by cc1477** [comment]
> 你键盘上是否有 Fn 键？

有的

**Comment by guyutongxue** [comment]
> > 你键盘上是否有 Fn 键？
> 
> 有的
> 

那有可能是 FnLock 锁定的问题？是否尝试过 Fn+F5 或 Fn+F6 ？

**Comment by cc1477** [comment]
> > > 你键盘上是否有 Fn 键？
> > 
> > 有的
> > 
> 
> 那有可能是 FnLock 锁定的问题？是否尝试过 Fn+F5 或 Fn+F6 ？

感谢，已解决
